### ISSUE TITLE
compiling issues on linux

### ISSUE THREAD

**Issue by beta-tester** [ShootMe/Klondike-Solver#3]
hi, i can compile the project on windows without any problems.
but if i try to compile on linux (ubuntu 15.10) i first get errors, about missing c++11 option.
by supplying the c++11 option i get an other error, that prevent the project from compiling straightly...

```
me@my-linux:~/dev/Klondike-Solver$ make all
g++ -std=c++11 -g -o KlondikeSolver KlondikeSolver.cpp
KlondikeSolver.cpp: In function ‘int main(int, char**)’:
KlondikeSolver.cpp:48:32: error: ‘_stricmp’ was not declared in this scope
   if (_stricmp(argv[i], "-draw") == 0 || _stricmp(argv[i], "/draw") == 0 || _stricmp(argv[i], "-dc") == 0 || _stricmp(argv[i], "/dc") == 0) {
                                ^
Makefile:4: recipe for target 'KlondikeSolver' failed
make: *** [KlondikeSolver] Error 1
```
